const solutionContent={
  online:['Accept Payments Anywhere','Your Customers Shop','Process credit cards, debit cards, ACH payments, and digital wallets through a secure payment gateway designed to maximize approvals and increase revenue.','MannyPay helps online businesses reduce friction at checkout, improve authorization rates, and grow globally with support for multiple currencies and payment methods.'],
  retail:['Smarter Checkout','For Every Counter','Connect reliable terminals and point-of-sale tools that make in-person payments faster, simpler, and easier to manage.','Bring payments, reporting, devices, and daily operations together with equipment selected around your workflow.'],
  zero:['Keep More','Of Every Sale','Explore compliant cash discount, dual pricing, and surcharge programs designed to help offset processing costs.','A MannyPay specialist can help identify the program that fits your business, customers, and local requirements.'],
  risk:['A Clearer Path','For Complex Businesses','Get tailored underwriting guidance, fraud controls, and payment options for regulated and harder-to-place industries.','We evaluate your business model, documentation, risk profile, and growth plan before finding the right processing route.'],
  international:['Accept Payments','Beyond Borders','Support customers across markets with secure payment acceptance, multiple currencies, and settlement options.','Build a checkout experience that makes international commerce feel local while keeping operations visible and manageable.'],
  secure:['More Confidence','At Online Checkout','Use 3D Secure authentication to strengthen fraud prevention and reduce avoidable chargeback exposure.','Give issuers and customers additional confidence without adding unnecessary friction to the purchase journey.']
};
document.querySelectorAll('[data-solution]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('[data-solution]').forEach(item=>{const selected=item===tab;item.classList.toggle('active',selected);item.setAttribute('aria-selected',String(selected))});const [line1,line2,copy,detail]=solutionContent[tab.dataset.solution];document.querySelector('#solution-title').innerHTML=`${line1}<br><em>${line2}</em>`;document.querySelector('#solution-copy').textContent=copy;document.querySelector('#solution-detail').textContent=detail}));

document.querySelectorAll('[data-product]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('[data-product]').forEach(item=>{const selected=item===tab;item.classList.toggle('active',selected);item.setAttribute('aria-selected',String(selected))});document.querySelectorAll('[data-category]').forEach(card=>{card.hidden=tab.dataset.product!=='all'&&!card.dataset.category.split(' ').includes(tab.dataset.product)})}));

document.querySelectorAll('[data-risk]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('[data-risk]').forEach(item=>{const selected=item===tab;item.classList.toggle('active',selected);item.setAttribute('aria-selected',String(selected))});document.querySelectorAll('[data-risk-card]').forEach(card=>{card.hidden=card.dataset.riskCard!==tab.dataset.risk})}));
