(()=>{
  const site=window.MANNYPAY_SITE;
  if(!site)return;
  const legacyName=document.body.dataset.studioNamespace||document.body.dataset.pageKey;
  const legacyPrefix=legacyName?`${legacyName.replace(/[^a-z0-9-]/gi,'-')}-mp`:'mp';
  [...document.body.querySelectorAll('*')].filter(element=>!['SCRIPT','STYLE','DIALOG'].includes(element.tagName)).forEach((element,index)=>{element.dataset.studioLegacyId=`${legacyPrefix}-${index+1}`});
  const href=site.href,current=document.body.dataset.pageKey||'home';
  const navHref=slug=>{const page=site.pages[slug];return page?.group==='Integrations'&&slug!=='integrations'?`${href('integrations')}#integration-${slug}`:href(slug)};
  const itemLink=slug=>{const page=site.pages[slug];return page?`<a class="mega-link${current===slug?' active':''}" href="${navHref(slug)}"><span>${page.title}</span><i class="material-symbols">arrow_outward</i></a>`:''};
  const desktopNav=site.nav.map((group,index)=>{
    const active=group.slug===current||group.columns.some(column=>column.items.includes(current));
    if(group.slug==='partners')return `<a class="nav-group-trigger nav-direct-link${active?' active':''}" href="${href(group.slug)}">Partners</a>`;
    return `<div class="nav-group"><a class="nav-group-trigger nav-primary-link${active?' active':''}" href="${href(group.slug)}" aria-expanded="false" aria-controls="mega-${index}">${group.label}<span class="material-symbols">keyboard_arrow_down</span></a><div class="mega-menu" id="mega-${index}"><div class="container mega-grid"><a class="mega-feature" href="${href(group.slug)}"><span class="material-symbols">payments</span><h2>${group.featured.title}</h2><p>${group.featured.copy}</p><b>Explore ${group.label} →</b></a><div class="mega-columns">${group.columns.map(column=>`<div><h3>${column.label}</h3>${column.items.map(itemLink).join('')}</div>`).join('')}</div></div></div></div>`;
  }).join('');
  const mobilePanels=site.nav.map((group,index)=>group.slug==='partners'?'':`<section class="mobile-level mobile-level-two" data-mobile-panel="group-${index}" aria-hidden="true"><button class="mobile-back" type="button" data-mobile-back><span class="material-symbols">arrow_back</span>Menu</button><header><small>Explore</small><h2>${group.label}</h2><a class="mobile-panel-feature" href="${href(group.slug)}">All ${group.label}<span>→</span></a></header>${group.columns.map((column,columnIndex)=>`<div class="mobile-branch"><button type="button" class="mobile-branch-trigger" aria-expanded="false" aria-controls="mobile-${index}-${columnIndex}">${column.label}<span class="material-symbols">add</span></button><div class="mobile-branch-items" id="mobile-${index}-${columnIndex}">${column.items.map(slug=>`<a href="${navHref(slug)}">${site.pages[slug].title}<span>→</span></a>`).join('')}</div></div>`).join('')}</section>`).join('');
  const header=document.querySelector('[data-site-header],.site-header');
  if(header)header.outerHTML=`<header class="site-header" data-site-header><div class="container nav-row"><a class="logo" href="index.html" aria-label="MannyPay home"><img src="assets/images/figma-home/mannypay-logo.png" alt="MannyPay"></a><nav class="desktop-nav" aria-label="Primary navigation">${desktopNav}</nav><div class="header-actions"><a class="wallet-link" href="${href('gateways')}"><span class="material-symbols">account_balance_wallet</span>Digital Wallet</a><button class="login-button" type="button" data-dialog="login"><span class="material-symbols">person</span>Login</button><button class="button button-primary" type="button" data-dialog="signup">Sign Up <span>→</span></button><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open menu"><i></i><i></i></button></div></div><nav class="mobile-menu" id="mobile-menu" aria-label="Mobile navigation"><div class="mobile-menu-track"><section class="mobile-level mobile-level-one"><div class="mobile-menu-top"><span>Menu</span><button class="mobile-close" type="button" aria-label="Close menu"><span class="material-symbols">close</span></button></div>${site.nav.map((group,index)=>group.slug==='partners'?`<a class="mobile-root-trigger mobile-root-link" href="${href(group.slug)}">${group.label}<span class="material-symbols">arrow_forward</span></a>`:`<button class="mobile-root-trigger" type="button" data-mobile-open="group-${index}">${group.label}<span class="material-symbols">arrow_forward</span></button>`).join('')}<a class="mobile-simple-link" href="${href('about')}">About Us</a><a class="mobile-simple-link" href="${href('contact')}">Contact Us</a><div class="mobile-menu-actions"><button class="login-button" type="button" data-dialog="login">Login</button><button class="button button-primary" type="button" data-dialog="signup">Sign Up →</button></div></section>${mobilePanels}</div></nav></header>`;

  const footer=document.querySelector('[data-site-footer],.site-footer');
  if(footer)footer.outerHTML=`<footer class="site-footer" data-site-footer><div class="container"><a class="footer-logo" href="index.html"><img src="assets/images/figma-home/mannypay-logo.png" alt="MannyPay"></a><div class="footer-grid">${site.nav.map(group=>`<div><h3>${group.label}</h3>${group.columns.flatMap(column=>column.items).slice(0,10).map(slug=>`<a href="${href(slug)}">${site.pages[slug].title}</a>`).join('')}</div>`).join('')}<div><h3>Company</h3>${['about','contact','careers','blog','upload','privacy-policy','terms-conditions'].map(slug=>`<a href="${href(slug)}">${site.pages[slug].title}</a>`).join('')}</div></div><div class="footer-legal"><p>MannyPay provides payment technology and merchant-service solutions through banking, processing, gateway, hardware, and other regulated partners. Product availability and terms vary by business and provider.</p><p>Copyright © 2026 MannyPay Global Inc. All Rights Reserved.</p></div></div></footer>`;

  const dialog=document.querySelector('#account-dialog');
  const closeDialog=()=>dialog?.close();
  document.querySelectorAll('[data-dialog]').forEach(button=>button.addEventListener('click',()=>{closeMenu();const signup=button.dataset.dialog==='signup';dialog.innerHTML=`<button class="dialog-close" type="button" aria-label="Close">×</button><h2>${signup?'Choose how to sign up':'Choose your account'}</h2><p>${signup?'Start as a merchant or join MannyPay as a partner.':'Access the portal associated with your account.'}</p>${signup?`<a href="${href('merchant-sign-up')}">Merchant Sign Up <span>→</span></a><a href="${href('referral-partner-sign-up')}">Referral Partner Sign Up <span>→</span></a><a href="${href('agent-iso-sign-up')}">Agent / ISO Sign Up <span>→</span></a>`:'<a href="#">Merchant Portal <span>→</span></a><a href="#">Partner / ISO Portal <span>→</span></a>'}`;dialog.querySelector('.dialog-close').addEventListener('click',closeDialog);dialog.showModal()}));
  dialog?.addEventListener('click',event=>{if(event.target===dialog)closeDialog()});

  const menuButton=document.querySelector('.menu-toggle'),mobileMenu=document.querySelector('.mobile-menu'),track=document.querySelector('.mobile-menu-track');
  function closeMenu(){menuButton?.setAttribute('aria-expanded','false');mobileMenu?.classList.remove('open');document.body.classList.remove('menu-open');track?.classList.remove('show-level-two');document.querySelectorAll('[data-mobile-panel]').forEach(panel=>panel.setAttribute('aria-hidden','true'))}
  menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));mobileMenu.classList.toggle('open',!open);document.body.classList.toggle('menu-open',!open)});
  document.querySelector('.mobile-close')?.addEventListener('click',closeMenu);
  mobileMenu?.addEventListener('click',event=>{const opener=event.target.closest('[data-mobile-open]');if(opener){const panel=document.querySelector(`[data-mobile-panel="${opener.dataset.mobileOpen}"]`);document.querySelectorAll('[data-mobile-panel]').forEach(item=>item.setAttribute('aria-hidden','true'));panel?.setAttribute('aria-hidden','false');track?.classList.add('show-level-two');return}if(event.target.closest('[data-mobile-back]'))track?.classList.remove('show-level-two')});
  document.querySelectorAll('.mobile-branch-trigger').forEach(button=>button.addEventListener('click',()=>{const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));button.parentElement.classList.toggle('open',!open);button.querySelector('.material-symbols').textContent=open?'add':'remove'}));
  mobileMenu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
  const desktopGroups=[...document.querySelectorAll('.desktop-nav .nav-group')];
  const closeDesktopMenus=except=>desktopGroups.forEach(group=>{if(group===except)return;group.classList.remove('open');group.querySelector('.nav-group-trigger')?.setAttribute('aria-expanded','false')});
  desktopGroups.forEach(group=>{const trigger=group.querySelector('.nav-group-trigger');trigger?.addEventListener('keydown',event=>{if(event.key!=='ArrowDown')return;event.preventDefault();const opening=!group.classList.contains('open');closeDesktopMenus(group);group.classList.toggle('open',opening);trigger.setAttribute('aria-expanded',String(opening))})});
  document.addEventListener('click',event=>{if(!event.target.closest('.desktop-nav .nav-group'))closeDesktopMenus()});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeDesktopMenus();closeMenu();closeDialog()}});
})();
